### ISSUE TITLE
Not working on VSCode Version 1.45.1

### ISSUE THREAD

**Issue by Pablodotnet** [microsoft/vscode-htmlhint#74] opened 2020-05-25 17:03 UTC
It is not recognizing the .htmlhintrc file on the latest version (1.45.1)

**Comment by zhengmz** [comment] 2020-05-27 06:42
me too

**Comment by jp7677** [comment] 2020-05-31 19:07
Do you have by chance any htmlhint settings in your VS-Code settings file (`.vscode/settings.json`)?
A PR of mine had been merged (https://github.com/microsoft/vscode-htmlhint/pull/70/files) but it should not have any effect in finding an existing `.htmlhintrc` file.

**Comment by jp7677** [comment] 2020-06-01 15:41
I have attached a PR which might fix this, the current code does not look for a `.htmlhintrc` file when htmlhint settings are set that does not override htmlhint configuration file or options. Would be cool if one of you could confirm that this fixes this issue.

**Closed** 2020-06-01 16:14 UTC

**Comment by Pablodotnet** [comment] 2020-06-01 16:56
Im not receiving the update

**Comment by jp7677** [comment] 2020-06-11 06:04
A new version has been published, could you please confirm that the issue is fixed (or not)?

**Comment by Pablodotnet** [comment] 2020-06-11 14:20
Confirm that is working now 😄

**Comment by jp7677** [comment] 2020-06-11 19:20
Nice, thanks for the confirmation!
